import Link from "next/link";
import { Search } from "lucide-react";
import { authorizedStoreScopeId, requirePermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";
import { businessDateRange } from "@/lib/reports/date-range";

export default async function SalesPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;from?:string;to?:string}>}){
  const user=await requirePermission("sale.view"); const {q="",status="ALL",from,to}=await searchParams;
  const start=from?businessDateRange(from):undefined; const end=to?businessDateRange(to,true):undefined;
  const allowedStatuses=["COMPLETED","PARTIAL_RETURN","RETURNED","CANCELLED"] as const;
  if ((from&&!start)||(to&&!end)||(from&&to&&from>to)||!allowedStatuses.includes(status as typeof allowedStatuses[number])&&status!=="ALL"||q.length>100) return <div><PageHeader title="Sales orders" description="Completed transactions, payments, and returns."/><p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">Invalid sales filters. Check the date range, status, and search length.</p></div>;
  const dateRange=start||end?{saleDate:{...(start?{gte:start}:{}),...(end?{lte:end}:{})}}:{};
  const storeId=authorizedStoreScopeId(user);
  const sales=await prisma.sale.findMany({where:{...(storeId?{storeId}:{}),...(status==="ALL"?{}:{status:status as typeof allowedStatuses[number]}),...dateRange,...(q?{OR:[{invoiceNumber:{contains:q}},{customer:{name:{contains:q}}}]}:{})},orderBy:{saleDate:"desc"},take:100,include:{customer:{select:{name:true}},store:{select:{name:true}},cashier:{select:{name:true}}}});
  return <div><PageHeader title="Sales orders" description="Completed transactions, payments, and returns."/><form className="mb-4 grid gap-2 sm:grid-cols-[1fr_150px_150px_160px_auto]"><label className="relative"><span className="sr-only">Search sales</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input name="q" defaultValue={q} placeholder="Invoice or customer" className="h-10 w-full rounded-lg border border-slate-300 bg-white pl-9 pr-3 text-sm"/></label><input name="from" type="date" defaultValue={from} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"/><input name="to" type="date" defaultValue={to} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"/><select name="status" defaultValue={status} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">All statuses</option><option value="COMPLETED">Completed</option><option value="PARTIAL_RETURN">Partial return</option><option value="RETURNED">Returned</option><option value="CANCELLED">Cancelled</option></select><button className="h-10 rounded-lg border border-slate-300 bg-white px-4 text-sm">Filter</button></form>{sales.length?<TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Invoice","Customer","Date","Store","Cashier","Total","Payment","Status"].map((label)=><th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{sales.map((sale)=><tr key={sale.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium"><Link href={`/sales/${sale.id}`} className="text-emerald-800 hover:underline">{sale.invoiceNumber}</Link></td><td className="px-4 py-3">{sale.customer?.name??"Walk-in"}</td><td className="px-4 py-3 text-slate-600">{formatDate(sale.saleDate)}</td><td className="px-4 py-3">{sale.store.name}</td><td className="px-4 py-3">{sale.cashier.name}</td><td className="px-4 py-3 text-right">{formatCurrency(sale.grandTotal.toString())}</td><td className="px-4 py-3"><StatusBadge value={sale.paymentStatus}/></td><td className="px-4 py-3"><StatusBadge value={sale.status}/></td></tr>)}</tbody></TableFrame>:<p className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No sales match those filters.</p>}{sales.length===100&&<p className="mt-3 text-xs text-slate-500">Showing 100 latest results. Refine the search or dates.</p>}</div>;
}
