"use client";

import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { createPurchaseAction } from "@/app/(dashboard)/purchases/actions";

type Option={id:string;name:string;sku?:string;sellingPrice?:string;costPrice?:string};type Store={id:string;name:string;warehouses:{id:string;name:string}[]};
export function PurchaseEditor({suppliers,stores,products}:{suppliers:Option[];stores:Store[];products:Option[]}){
 const [storeId,setStoreId]=useState(stores[0]?.id??"");const [warehouseId,setWarehouseId]=useState(stores[0]?.warehouses[0]?.id??"");const [lines,setLines]=useState([{productId:products[0]?.id??"",quantity:"1",unitCost:products[0]?.costPrice??"0"}]);const field="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm";
 const availableWarehouses=stores.find((store)=>store.id===storeId)?.warehouses??[];
 function selectStore(next:string){setStoreId(next);setWarehouseId(stores.find((store)=>store.id===next)?.warehouses[0]?.id??"");}
 function selectProduct(index:number,productId:string){const product=products.find((item)=>item.id===productId);setLines((previous)=>previous.map((line,i)=>i===index?{...line,productId,unitCost:product?.costPrice??"0"}:line));}
 return <form action={createPurchaseAction} className="space-y-5 rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Supplier<select required name="supplierId" className={field}>{suppliers.map((supplier)=><option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label className="text-sm font-medium">Store<select required value={storeId} name="storeId" onChange={(event)=>selectStore(event.target.value)} className={field}>{stores.map((store)=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label className="text-sm font-medium">Warehouse<select required value={warehouseId} name="warehouseId" onChange={(event)=>setWarehouseId(event.target.value)} className={field}>{availableWarehouses.map((warehouse)=><option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label></div>
 <div><div className="mb-2 flex items-center justify-between"><h2 className="font-semibold">Purchase items</h2><button type="button" onClick={()=>setLines((items)=>[...items,{productId:products[0]?.id??"",quantity:"1",unitCost:products[0]?.costPrice??"0"}])} className="inline-flex items-center gap-1 text-sm font-medium text-emerald-800"><Plus size={15}/> Add line</button></div><div className="space-y-2">{lines.map((line,index)=><div key={index} className="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-[minmax(0,1fr)_120px_160px_40px]"><label className="text-xs font-medium text-slate-600">Product<select required value={line.productId} onChange={(event)=>selectProduct(index,event.target.value)} className={`${field} mt-1`}>{products.map((product)=><option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select></label><label className="text-xs font-medium text-slate-600">Quantity<input required type="number" min="0.001" step="0.001" value={line.quantity} onChange={(event)=>setLines((items)=>items.map((item,i)=>i===index?{...item,quantity:event.target.value}:item))} className={`${field} mt-1`}/></label><label className="text-xs font-medium text-slate-600">Unit cost<input required type="number" min="0" step="0.01" value={line.unitCost} onChange={(event)=>setLines((items)=>items.map((item,i)=>i===index?{...item,unitCost:event.target.value}:item))} className={`${field} mt-1`}/></label><button type="button" aria-label="Remove line" disabled={lines.length===1} onClick={()=>setLines((items)=>items.filter((_,i)=>i!==index))} className="self-end rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-700 disabled:opacity-30"><Trash2 size={16}/></button></div>)}</div><input type="hidden" name="items" value={JSON.stringify(lines.map((line)=>({productId:line.productId,quantity:Number(line.quantity),unitCost:Number(line.unitCost)})))}/></div>
 <label className="block text-sm font-medium">Notes<textarea name="notes" maxLength={4000} rows={3} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"/></label><button disabled={!suppliers.length||!stores.length||!products.length} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Create purchase</button></form>;
}
