import { authorizedStoreScopeId, requirePermission, hasPermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";
import { createExpense } from "@/app/(dashboard)/expenses/actions";

export default async function ExpensesPage({searchParams}:{searchParams:Promise<{created?:string;error?:string}>}){
 const user=await requirePermission("expense.manage");const query=await searchParams;const storeId=authorizedStoreScopeId(user);
 const [expenses,categories,stores,methods]=await Promise.all([
  prisma.expense.findMany({where:storeId?{storeId}:{},orderBy:{expenseDate:"desc"},take:100,include:{category:{select:{name:true}},store:{select:{name:true}},createdBy:{select:{name:true}}}}),
  hasPermission(user,"expense.create")?prisma.expenseCategory.findMany({orderBy:{name:"asc"}}):Promise.resolve([]),
  hasPermission(user,"expense.create")?prisma.store.findMany({where:{status:"ACTIVE",...(storeId?{id:storeId}:{})},orderBy:{name:"asc"},select:{id:true,name:true}}):Promise.resolve([]),
  hasPermission(user,"expense.create")?prisma.paymentMethod.findMany({where:{active:true},orderBy:{name:"asc"},select:{type:true,name:true}}):Promise.resolve([]),
 ]);
 return <div><PageHeader title="Expenses" description="Track store expenses and supporting information."/>{query.created&&<p role="status" className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Expense saved as draft.</p>}{query.error&&<p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">Expense could not be saved. Check the entered values.</p>}
 {expenses.length?<TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Number","Date","Category","Store","Created by","Amount","Status"].map((label)=><th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{expenses.map((expense)=><tr key={expense.id}><td className="px-4 py-3 font-mono text-xs">{expense.number}</td><td className="px-4 py-3">{formatDate(expense.expenseDate)}</td><td className="px-4 py-3">{expense.category.name}</td><td className="px-4 py-3">{expense.store.name}</td><td className="px-4 py-3">{expense.createdBy.name}</td><td className="px-4 py-3 text-right">{formatCurrency(expense.amount.toString())}</td><td className="px-4 py-3"><StatusBadge value={expense.status}/></td></tr>)}</tbody></TableFrame>:<p className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No expenses have been recorded.</p>}
 {hasPermission(user,"expense.create")&&<form action={createExpense} className="mt-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-3"><h2 className="font-semibold sm:col-span-2 xl:col-span-3">Record expense</h2><select name="categoryId" required className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">Category</option>{categories.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="storeId" required className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">Store</option>{stores.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="amount" type="number" step="0.01" min="0.01" required placeholder="Amount" className="h-10 rounded-lg border border-slate-300 px-3 text-sm"/><input name="expenseDate" type="date" required className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"/><select name="paymentMethod" required className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm">{methods.map((item)=><option key={item.type} value={item.type}>{item.name}</option>)}</select><input name="description" maxLength={4000} placeholder="Description" className="h-10 rounded-lg border border-slate-300 px-3 text-sm"/><button className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-medium text-white sm:col-span-2 xl:col-span-3">Save expense draft</button></form>}
 </div>;
}
