import Link from "next/link";
import { ArrowUpRight, BarChart3, Boxes, ShieldCheck, Store } from "lucide-react";

export default function Home() {
  return (
    <main className="min-h-screen bg-[#f7f9fb]">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-700 p-2.5 text-white"><Store size={22}/></div><span className="font-semibold text-slate-900">Retail Management</span></div><Link href="/login" className="rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-medium text-white">Staff sign in <ArrowUpRight className="ml-1 inline" size={16}/></Link></header>
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-6 py-20 md:grid-cols-[1.15fr_.85fr] md:py-28"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-800"><ShieldCheck size={14}/> One workspace for everyday retail operations</p><h1 className="max-w-2xl text-5xl font-semibold leading-tight tracking-tight text-slate-950 md:text-6xl">Run your retail business with clarity.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Manage products, inventory, purchasing and sales across your stores from one secure workspace.</p><Link href="/login" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-6 py-3 font-medium text-white">Open your workspace <ArrowUpRight size={17}/></Link></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/60"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="text-sm text-slate-500">Operations overview</p><p className="mt-1 font-semibold text-slate-900">Your business, in sync</p></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-800"><BarChart3/></div></div><div className="grid grid-cols-2 gap-4 py-5"><div className="rounded-xl bg-slate-50 p-4"><Boxes className="text-emerald-700" size={20}/><p className="mt-3 text-sm font-medium text-slate-800">Inventory control</p><p className="mt-1 text-xs text-slate-500">Stock movement visibility</p></div><div className="rounded-xl bg-slate-50 p-4"><Store className="text-emerald-700" size={20}/><p className="mt-3 text-sm font-medium text-slate-800">Multi-store ready</p><p className="mt-1 text-xs text-slate-500">One view of each location</p></div></div><div className="rounded-xl bg-emerald-900 p-5 text-white"><p className="text-sm text-emerald-100">Built for daily retail work</p><p className="mt-2 text-xl font-medium">Sales, stock and purchasing together.</p></div></div></section>
    </main>
  );
}
