import Link from "next/link";
import { Prisma } from "@prisma/client";
import { hasRole, requirePermission, assertStoreAccess } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";
import { PrintButton } from "@/components/ui/print-button";
import { businessDateRange } from "@/lib/reports/date-range";

const modes = ["sales", "purchases", "inventory", "payments", "returns", "customers", "suppliers", "profit"] as const;
type Mode = typeof modes[number];
const titles: Record<Mode, string> = { sales: "Sales", purchases: "Purchases", inventory: "Inventory", payments: "Payments", returns: "Returns / refunds", customers: "Customers", suppliers: "Suppliers", profit: "Profit summary" };
const parseDate = (value?: string, end = false) => value ? businessDateRange(value, end) : undefined;
const currency = (value: Prisma.Decimal | null | undefined) => formatCurrency(value?.toString() ?? "0");

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ type?: string; from?: string; to?: string; status?: string; payment?: string; storeId?: string }> }) {
  const user = await requirePermission("report.view");
  const params = await searchParams;
  const mode: Mode = modes.includes(params.type as Mode) ? params.type as Mode : "sales";
  const start = parseDate(params.from);
  const end = parseDate(params.to, true);
  const invalidDates = Boolean(params.from && !start || params.to && !end || params.from && params.to && params.from > params.to);
  const isSuperAdmin = hasRole(user, "SUPER_ADMIN");
  if (params.storeId) assertStoreAccess(user, params.storeId);
  if (invalidDates) return <div><PageHeader title="Reports & analytics" description="Store-scoped operational summaries calculated from recorded transactions."/><p role="alert" className="mt-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">The date range is invalid. Use valid YYYY-MM-DD dates and ensure the start is not after the end.</p></div>;
  const storeId = params.storeId !== undefined ? params.storeId || undefined : isSuperAdmin ? undefined : user.storeId ?? "__no_store_scope__";
  const storeFilter: Prisma.StringFilter | undefined = storeId ? { equals: storeId } : undefined;
  const stores = isSuperAdmin ? await prisma.store.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" }, select: { id: true, name: true } }) : [];
  const dateSale = start || end ? { ...(start ? { gte: start } : {}), ...(end ? { lte: end } : {}) } : undefined;
  const saleStatuses = ["COMPLETED", "PARTIAL_RETURN", "RETURNED", "CANCELLED"];
  const paymentStatuses = ["UNPAID", "PARTIAL", "PAID", "REFUNDED"];
  const purchaseStatuses = ["DRAFT", "PENDING", "APPROVED", "PARTIALLY_RECEIVED", "RECEIVED", "COMPLETED", "CANCELLED"];
  const saleWhere: Prisma.SaleWhereInput = {
    ...(storeFilter ? { storeId: storeFilter } : {}),
    ...(dateSale ? { saleDate: dateSale } : {}),
    ...(mode === "sales" && params.status && saleStatuses.includes(params.status) ? { status: params.status as Prisma.EnumSaleStatusFilter["equals"] } : { status: { in: ["COMPLETED", "PARTIAL_RETURN", "RETURNED"] } }),
    ...(mode === "sales" && params.payment && paymentStatuses.includes(params.payment) ? { paymentStatus: params.payment as Prisma.EnumPaymentStatusFilter["equals"] } : {}),
  };
  const purchaseWhere: Prisma.PurchaseWhereInput = {
    ...(storeFilter ? { storeId: storeFilter } : {}),
    ...(dateSale ? { purchaseDate: dateSale } : {}),
    ...(mode === "purchases" && params.status && purchaseStatuses.includes(params.status) ? { status: params.status as Prisma.EnumPurchaseStatusFilter["equals"] } : { status: { not: "CANCELLED" } }),
  };
  const settlementWhere: Prisma.RefundSettlementWhereInput = { ...(storeFilter ? { storeId: storeFilter } : {}), ...(start || end ? { settledAt: { ...(start ? { gte: start } : {}), ...(end ? { lte: end } : {}) } } : {}) };
  const [sales, saleSummary, refunds, purchases, purchaseSummary, inventory, settlements, salesByMethod, refundsByMethod, customerGroups, supplierGroups, marginRows] = await Promise.all([
    mode === "sales" ? prisma.sale.findMany({ where: saleWhere, orderBy: { saleDate: "desc" }, take: 250, select: { id: true, invoiceNumber: true, saleDate: true, status: true, paymentStatus: true, subtotal: true, discount: true, tax: true, grandTotal: true, refunds: { where: { ...(start || end ? { settledAt: { ...(start ? { gte: start } : {}), ...(end ? { lte: end } : {}) } } : {}) }, select: { amount: true } }, customer: { select: { name: true } }, store: { select: { name: true } } } }) : Promise.resolve([]),
    mode === "sales" ? prisma.sale.aggregate({ where: saleWhere, _count: { _all: true }, _sum: { subtotal: true, discount: true, tax: true, grandTotal: true } }) : Promise.resolve(null),
    mode === "sales" ? prisma.refundSettlement.aggregate({ where: { ...settlementWhere, sale: saleWhere }, _sum: { amount: true } }) : Promise.resolve(null),
    mode === "purchases" ? prisma.purchase.findMany({ where: purchaseWhere, orderBy: { purchaseDate: "desc" }, take: 250, select: { id: true, invoiceNumber: true, purchaseDate: true, status: true, paymentStatus: true, grandTotal: true, supplier: { select: { name: true } }, store: { select: { name: true } } } }) : Promise.resolve([]),
    mode === "purchases" ? prisma.purchase.aggregate({ where: purchaseWhere, _count: { _all: true }, _sum: { grandTotal: true } }) : Promise.resolve(null),
    mode === "inventory" ? prisma.inventory.findMany({ where: storeId ? { warehouse: { storeId } } : {}, orderBy: { product: { name: "asc" } }, take: 1001, select: { id: true, quantity: true, reservedQuantity: true, averageCost: true, warehouse: { select: { name: true, store: { select: { name: true } } } }, product: { select: { name: true, sku: true, minimumStock: true } } } }) : Promise.resolve([]),
    mode === "returns" ? prisma.refundSettlement.findMany({ where: settlementWhere, orderBy: { settledAt: "desc" }, take: 251, select: { id: true, refundNumber: true, settledAt: true, method: true, amount: true, sale: { select: { id: true, invoiceNumber: true } }, saleReturn: { select: { number: true, reason: true } }, store: { select: { name: true } }, processedBy: { select: { name: true } } } }) : Promise.resolve([]),
    mode === "payments" ? prisma.salePayment.groupBy({ by: ["method"], where: { sale: { ...saleWhere, ...(start || end ? { saleDate: { ...(start ? { gte: start } : {}), ...(end ? { lte: end } : {}) } } : {}) } }, _sum: { amount: true }, _count: { _all: true } }) : Promise.resolve([]),
    mode === "payments" ? prisma.refundSettlement.groupBy({ by: ["method"], where: settlementWhere, _sum: { amount: true }, _count: { _all: true } }) : Promise.resolve([]),
    mode === "customers" ? prisma.sale.groupBy({ by: ["customerId"], where: { ...saleWhere, customerId: { not: null } }, _sum: { grandTotal: true }, _count: { _all: true }, orderBy: { _sum: { grandTotal: "desc" } }, take: 250 }) : Promise.resolve([]),
    mode === "suppliers" ? prisma.purchase.groupBy({ by: ["supplierId"], where: purchaseWhere, _sum: { grandTotal: true }, _count: { _all: true }, orderBy: { _sum: { grandTotal: "desc" } }, take: 250 }) : Promise.resolve([]),
    mode === "profit" ? prisma.$queryRaw<Array<{ grossMargin: Prisma.Decimal }>>(Prisma.sql`SELECT COALESCE(SUM(s.subtotal - s.discount - s.tax - COALESCE(costs.cost, 0) + COALESCE(returned.returnedCost, 0) - COALESCE(refunds.amount * (s.grandTotal - s.tax) / NULLIF(s.grandTotal, 0), 0)), 0) AS grossMargin FROM Sale s LEFT JOIN (SELECT saleId, SUM(unitCost * quantity) AS cost FROM SaleItem GROUP BY saleId) costs ON costs.saleId = s.id LEFT JOIN (SELECT sr.saleId, SUM(ri.quantity * si.unitCost) AS returnedCost FROM SaleReturn sr INNER JOIN SaleReturnItem ri ON ri.returnId = sr.id INNER JOIN SaleItem si ON si.id = ri.saleItemId GROUP BY sr.saleId) returned ON returned.saleId = s.id LEFT JOIN (SELECT saleId, SUM(amount) AS amount FROM RefundSettlement GROUP BY saleId) refunds ON refunds.saleId = s.id WHERE s.status IN ('COMPLETED', 'PARTIAL_RETURN', 'RETURNED') ${storeId ? Prisma.sql`AND s.storeId = ${storeId}` : Prisma.empty} ${start ? Prisma.sql`AND s.saleDate >= ${start}` : Prisma.empty} ${end ? Prisma.sql`AND s.saleDate <= ${end}` : Prisma.empty}`) : Promise.resolve([]),
  ]);
  const customerIds = customerGroups.map((row) => row.customerId).filter((id): id is string => Boolean(id));
  const supplierIds = supplierGroups.map((row) => row.supplierId);
  const [customerRecords, supplierRecords] = await Promise.all([
    customerIds.length ? prisma.customer.findMany({ where: { id: { in: customerIds } }, select: { id: true, customerCode: true, name: true } }) : Promise.resolve([]),
    supplierIds.length ? prisma.supplier.findMany({ where: { id: { in: supplierIds } }, select: { id: true, supplierCode: true, name: true } }) : Promise.resolve([]),
  ]);
  const customerById = new Map(customerRecords.map((row) => [row.id, row]));
  const supplierById = new Map(supplierRecords.map((row) => [row.id, row]));
  const paramsUrl = `from=${params.from ?? ""}&to=${params.to ?? ""}${storeId && isSuperAdmin ? `&storeId=${storeId}` : ""}${(mode === "sales" || mode === "purchases") && params.status ? `&status=${params.status}` : ""}${mode === "sales" && params.payment ? `&payment=${params.payment}` : ""}`;
  const exportType = mode === "returns" ? "refunds" : mode;
  const inventoryRowsShown = inventory.slice(0, 1000);
  const settlementsShown = settlements.slice(0, 250);
  const rowsAvailable = sales.length || purchases.length || inventoryRowsShown.length || settlementsShown.length || customerGroups.length || supplierGroups.length;
  return <div className="space-y-5"><PageHeader title="Reports & analytics" description="Store-scoped operational summaries calculated from recorded transactions." action={<div className="flex gap-2"><a href={`/api/reports/export?type=${exportType}&${paramsUrl}`} className="print:hidden inline-flex h-10 items-center rounded-lg bg-emerald-700 px-4 text-sm font-medium text-white">Export CSV</a><PrintButton /></div>} />
    <nav className="print:hidden flex gap-2 overflow-x-auto border-b border-slate-200">{modes.map((item) => <Link key={item} href={`/reports?type=${item}&${paramsUrl}`} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${mode === item ? "border-emerald-700 font-semibold text-emerald-800" : "border-transparent text-slate-500"}`}>{titles[item]}</Link>)}</nav>
    <form className="print:hidden grid gap-2 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1fr_160px_160px_auto]"><input type="hidden" name="type" value={mode}/>{mode!=="inventory"&&<><label className="text-xs font-medium text-slate-500">From<input name="from" type="date" defaultValue={params.from} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"/></label><label className="text-xs font-medium text-slate-500">To<input name="to" type="date" defaultValue={params.to} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"/></label></>}{isSuperAdmin&&<label className="text-xs font-medium text-slate-500">Store<select name="storeId" defaultValue={params.storeId??(isSuperAdmin?"":user.storeId??"")} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="">All stores</option>{stores.map((store)=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label>}
      {mode==="sales"&&<><select name="status" defaultValue={params.status??"ALL"} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">Sale status</option>{saleStatuses.map((status)=><option key={status}>{status}</option>)}</select><select name="payment" defaultValue={params.payment??"ALL"} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">Payment status</option>{paymentStatuses.map((status)=><option key={status}>{status}</option>)}</select></>}
      {mode==="purchases"&&<select name="status" defaultValue={params.status??"ALL"} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">Purchase status</option>{purchaseStatuses.map((status)=><option key={status}>{status}</option>)}</select>}<button className="h-10 rounded-lg border border-slate-300 bg-white px-4 text-sm">Apply filters</button></form>
    {invalidDates&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">The date range is invalid.</p>}
    <section className="print-report">
    {mode==="sales"&&saleSummary&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Transactions" value={saleSummary._count._all.toLocaleString("id-ID")}/><Metric label="Gross item subtotal" value={currency(saleSummary._sum.subtotal)}/><Metric label="Discounts" value={currency(saleSummary._sum.discount)}/><Metric label="Tax" value={currency(saleSummary._sum.tax)}/><Metric label="Refunds" value={currency(refunds?._sum.amount)}/><Metric label="Net after refunds" value={currency((saleSummary._sum.grandTotal??new Prisma.Decimal(0)).minus(refunds?._sum.amount??0))}/></div><p className="text-xs text-slate-500">Net after refunds = recorded sale grand totals less refunds settled in the selected refund date range. This is cash-flow reporting, not accounting revenue recognition.</p>{sales.length?<TableFrame><thead><tr>{["Date","Invoice","Customer","Store","Subtotal","Discount","Tax","Total","Refund","Net","Payment","Status"].map((name)=><th key={name} className="px-3 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{sales.map((sale)=>{const refund=sale.refunds.reduce((sum,row)=>sum.plus(row.amount),new Prisma.Decimal(0));return <tr key={sale.id}><td className="px-3 py-3">{formatDate(sale.saleDate)}</td><td className="px-3 py-3"><Link href={`/sales/${sale.id}`} className="text-emerald-800">{sale.invoiceNumber}</Link></td><td className="px-3 py-3">{sale.customer?.name??"Walk-in"}</td><td className="px-3 py-3">{sale.store.name}</td><td className="px-3 py-3">{currency(sale.subtotal)}</td><td className="px-3 py-3">{currency(sale.discount)}</td><td className="px-3 py-3">{currency(sale.tax)}</td><td className="px-3 py-3">{currency(sale.grandTotal)}</td><td className="px-3 py-3">{currency(refund)}</td><td className="px-3 py-3">{currency(sale.grandTotal.minus(refund))}</td><td className="px-3 py-3"><StatusBadge value={sale.paymentStatus}/></td><td className="px-3 py-3"><StatusBadge value={sale.status}/></td></tr>})}</tbody></TableFrame>:<Empty/>}{saleSummary._count._all>sales.length&&<p className="text-xs text-slate-500">Showing latest {sales.length} of {saleSummary._count._all} transactions; summary totals cover all filtered records.</p>}</>}
    {mode==="purchases"&&purchaseSummary&&<><div className="grid gap-3 sm:grid-cols-2"><Metric label="Purchases" value={purchaseSummary._count._all.toLocaleString("id-ID")}/><Metric label="Purchase total" value={currency(purchaseSummary._sum.grandTotal)}/></div>{purchases.length?<TableFrame><thead><tr>{["Date","Purchase","Supplier","Store","Total","Payment","Status"].map((name)=><th key={name} className="px-4 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{purchases.map((purchase)=><tr key={purchase.id}><td className="px-4 py-3">{formatDate(purchase.purchaseDate)}</td><td className="px-4 py-3"><Link href={`/purchases/${purchase.id}`} className="text-emerald-800">{purchase.invoiceNumber}</Link></td><td className="px-4 py-3">{purchase.supplier.name}</td><td className="px-4 py-3">{purchase.store.name}</td><td className="px-4 py-3">{currency(purchase.grandTotal)}</td><td className="px-4 py-3"><StatusBadge value={purchase.paymentStatus}/></td><td className="px-4 py-3"><StatusBadge value={purchase.status}/></td></tr>)}</tbody></TableFrame>:<Empty/>}{purchaseSummary._count._all>purchases.length&&<p className="text-xs text-slate-500">Showing latest {purchases.length} of {purchaseSummary._count._all} purchases; summary covers all records.</p>}</>}
    {mode==="inventory"&&<><p className="mb-3 text-xs text-slate-500">Current inventory snapshot. Date filters do not apply. Showing up to 1,000 inventory rows; value is on-hand quantity × recorded average cost.</p>{inventoryRowsShown.length?<TableFrame><thead><tr>{["Product","SKU","Store","Warehouse","On hand","Reserved","Available","Minimum","Value"].map((name)=><th key={name} className="px-3 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{inventoryRowsShown.map((item)=>{const available=item.quantity.minus(item.reservedQuantity);return <tr key={item.id}><td className="px-3 py-3">{item.product.name}</td><td className="px-3 py-3">{item.product.sku}</td><td className="px-3 py-3">{item.warehouse.store.name}</td><td className="px-3 py-3">{item.warehouse.name}</td><td className="px-3 py-3">{item.quantity.toString()}</td><td className="px-3 py-3">{item.reservedQuantity.toString()}</td><td className="px-3 py-3">{available.toString()}</td><td className="px-3 py-3">{item.product.minimumStock.toString()}</td><td className="px-3 py-3">{currency(item.quantity.times(item.averageCost))}</td></tr>})}</tbody></TableFrame>:<Empty/>}{inventory.length>1000&&<p className="mt-2 text-xs text-slate-500">The display limit of 1,000 rows was reached. Use the store filter or CSV export for the full listing.</p>}</>}
    {mode==="payments"&&<div className="grid gap-5 lg:grid-cols-2"><section><h2 className="mb-2 font-semibold">Sales payments</h2>{salesByMethod.length?<TableFrame><thead><tr><th className="px-4 py-3">Method</th><th className="px-4 py-3">Transactions</th><th className="px-4 py-3">Amount</th></tr></thead><tbody>{salesByMethod.map((row)=><tr key={row.method}><td className="px-4 py-3">{row.method}</td><td className="px-4 py-3">{row._count._all}</td><td className="px-4 py-3">{currency(row._sum.amount)}</td></tr>)}</tbody></TableFrame>:<Empty/>}</section><section><h2 className="mb-2 font-semibold">Refund payments (separate)</h2>{refundsByMethod.length?<TableFrame><thead><tr><th className="px-4 py-3">Method</th><th className="px-4 py-3">Refunds</th><th className="px-4 py-3">Amount</th></tr></thead><tbody>{refundsByMethod.map((row)=><tr key={row.method}><td className="px-4 py-3">{row.method}</td><td className="px-4 py-3">{row._count._all}</td><td className="px-4 py-3">{currency(row._sum.amount)}</td></tr>)}</tbody></TableFrame>:<Empty/>}</section></div>}
    {mode==="returns"&&<><p className="mb-3 text-xs text-slate-500">This report lists refund settlements. Historical returns created before refund settlements were introduced remain returns without a recorded settlement and are not counted as paid refunds.</p>{settlementsShown.length?<TableFrame><thead><tr>{["Date","Refund","Sale","Return","Store","Method","Amount","User"].map((name)=><th key={name} className="px-3 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{settlementsShown.map((row)=><tr key={row.id}><td className="px-3 py-3">{formatDate(row.settledAt)}</td><td className="px-3 py-3">{row.refundNumber}</td><td className="px-3 py-3"><Link className="text-emerald-800" href={`/sales/${row.sale.id}`}>{row.sale.invoiceNumber}</Link></td><td className="px-3 py-3" title={row.saleReturn.reason}>{row.saleReturn.number}</td><td className="px-3 py-3">{row.store.name}</td><td className="px-3 py-3">{row.method}</td><td className="px-3 py-3">{currency(row.amount)}</td><td className="px-3 py-3">{row.processedBy.name}</td></tr>)}</tbody></TableFrame>:<Empty/>}{settlements.length>250&&<p className="mt-2 text-xs text-slate-500">Showing latest 250 settlements; CSV export supports up to 10,000.</p>}</>}
    {mode==="customers"&&(customerGroups.length?<><p className="mb-2 text-xs text-slate-500">Top 250 customers by filtered sales total. Totals are aggregated across all matching database records.</p><TableFrame><thead><tr>{["Customer","Transactions","Total sales","Average transaction"].map((name)=><th key={name} className="px-4 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{customerGroups.map((row)=>{const customer=customerById.get(row.customerId!);const total=row._sum.grandTotal??new Prisma.Decimal(0);return <tr key={row.customerId}><td className="px-4 py-3">{customer?.customerCode} · {customer?.name}</td><td className="px-4 py-3">{row._count._all}</td><td className="px-4 py-3">{currency(total)}</td><td className="px-4 py-3">{currency(total.dividedBy(row._count._all))}</td></tr>})}</tbody></TableFrame></>:<Empty/>)}
    {mode==="suppliers"&&(supplierGroups.length?<><p className="mb-2 text-xs text-slate-500">Top 250 suppliers by filtered purchase total. Totals are aggregated across all matching database records.</p><TableFrame><thead><tr>{["Supplier","Purchases","Purchase total","Average purchase"].map((name)=><th key={name} className="px-4 py-3 text-xs font-medium">{name}</th>)}</tr></thead><tbody>{supplierGroups.map((row)=>{const supplier=supplierById.get(row.supplierId);const total=row._sum.grandTotal??new Prisma.Decimal(0);return <tr key={row.supplierId}><td className="px-4 py-3">{supplier?.supplierCode} · {supplier?.name}</td><td className="px-4 py-3">{row._count._all}</td><td className="px-4 py-3">{currency(total)}</td><td className="px-4 py-3">{currency(total.dividedBy(row._count._all))}</td></tr>})}</tbody></TableFrame></>:<Empty/>)}
    {mode==="profit"&&<article className="max-w-xl rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Estimated gross margin after returns</p><p className="mt-2 text-3xl font-semibold">{currency(marginRows[0]?.grossMargin ?? new Prisma.Decimal(0))}</p><p className="mt-3 text-xs leading-5 text-slate-500">Calculated in MySQL from sale subtotal less sale discounts and tax, recorded item cost, restored return cost, and settled refunds before tax. Excludes operating expenses and accounting adjustments; this is not net profit.</p></article>}
    {!rowsAvailable&&["sales","purchases","inventory","returns","customers","suppliers"].includes(mode)&&mode!=="sales"&&mode!=="purchases"&&<Empty/>}
    </section>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></article>; }
function Empty() { return <p className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No records match the selected filters.</p>; }
