import Link from "next/link";
import { Activity, ArrowRight, Boxes, CircleDollarSign, Package, ShoppingBag, ShoppingCart } from "lucide-react";
import { prisma } from "@/lib/db/prisma";
import { requireUser } from "@/lib/auth/permissions";
import { formatCurrency, formatDate } from "@/lib/utils";
import { calculateAvailableQuantity } from "@/lib/services/inventory-quantity";
import { SalesChart } from "@/components/dashboard/sales-chart";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";
import { Prisma } from "@prisma/client";
import { businessDateParts, businessDayKey, businessDayStart } from "@/lib/reports/date-range";

export default async function DashboardPage() {
  const user = await requireUser("dashboard.view");
  const now = new Date();
  const today = businessDayStart(now);
  const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);
  const from = new Date(today.getTime() - 6 * 24 * 60 * 60 * 1000);
  const todayParts = businessDateParts(today);
  const monthStart = new Date(`${todayParts.year}-${todayParts.month}-01T00:00:00+07:00`);
  const scopeStoreId = user.roles.includes("SUPER_ADMIN") ? undefined : user.storeId ?? "__no_store_scope__";
  const storeFilter = scopeStoreId ? { storeId: scopeStoreId } : {};
  const [todaySales, todayTransactions, productCount, customerCount, supplierCount, pendingPurchases, pendingOrders, inventoryValueRows, recentSales, weekSales, activity, store, monthSales, weekSummary, monthRefunds, topProductRows, lowStockCountRows] = await Promise.all([
    prisma.sale.aggregate({ where: { ...storeFilter, saleDate: { gte: today, lt: tomorrow }, status: "COMPLETED" }, _sum: { grandTotal: true } }),
    prisma.sale.count({ where: { ...storeFilter, saleDate: { gte: today, lt: tomorrow }, status: "COMPLETED" } }),
    prisma.product.count({ where: { status: "ACTIVE" } }),
    prisma.customer.count({ where: { status: "ACTIVE", ...(scopeStoreId ? { sales: { some: { storeId: scopeStoreId } } } : {}) } }),
    prisma.supplier.count({ where: { status: "ACTIVE", ...(scopeStoreId ? { purchases: { some: { storeId: scopeStoreId } } } : {}) } }),
    prisma.purchase.count({ where: { ...storeFilter, status: { in: ["PENDING", "APPROVED", "PARTIALLY_RECEIVED"] } } }),
    prisma.sale.count({ where: { ...storeFilter, status: "DRAFT" } }),
    prisma.$queryRaw<Array<{ stockValue: Prisma.Decimal }>>(Prisma.sql`SELECT COALESCE(SUM(i.quantity * i.averageCost), 0) AS stockValue FROM Inventory i INNER JOIN Warehouse w ON w.id = i.warehouseId ${scopeStoreId ? Prisma.sql`WHERE w.storeId = ${scopeStoreId}` : Prisma.empty}`),
    prisma.sale.findMany({ where: { ...storeFilter, saleDate: { lt: tomorrow }, status: { in: ["COMPLETED", "PARTIAL_RETURN", "RETURNED"] } }, orderBy: { saleDate: "desc" }, take: 6, select: { invoiceNumber: true, saleDate: true, grandTotal: true, paymentStatus: true, status: true, customer: { select: { name: true } } } }),
    prisma.$queryRaw<Array<{ dayKey: string; total: Prisma.Decimal }>>(Prisma.sql`SELECT DATE_FORMAT(DATE_ADD(s.saleDate, INTERVAL 7 HOUR), '%Y-%m-%d') AS dayKey, SUM(s.grandTotal) AS total FROM Sale s WHERE s.status = 'COMPLETED' AND s.saleDate >= ${from} AND s.saleDate < ${tomorrow} ${scopeStoreId ? Prisma.sql`AND s.storeId = ${scopeStoreId}` : Prisma.empty} GROUP BY DATE_FORMAT(DATE_ADD(s.saleDate, INTERVAL 7 HOUR), '%Y-%m-%d')`),
    prisma.auditLog.findMany({ where: scopeStoreId ? { user: { storeId: scopeStoreId } } : {}, orderBy: { createdAt: "desc" }, take: 5, select: { action: true, module: true, createdAt: true, entity: true } }),
    scopeStoreId ? prisma.store.findUnique({ where: { id: scopeStoreId }, select: { name: true, code: true } }) : Promise.resolve(null),
    prisma.sale.aggregate({ where: { ...storeFilter, status: "COMPLETED", saleDate: { gte: monthStart, lt: tomorrow } }, _sum: { grandTotal: true }, _count: { _all: true } }),
    prisma.sale.aggregate({ where: { ...storeFilter, status: "COMPLETED", saleDate: { gte: from, lt: tomorrow } }, _sum: { grandTotal: true }, _count: { _all: true } }),
    prisma.refundSettlement.aggregate({ where: { ...storeFilter, settledAt: { gte: monthStart, lt: tomorrow } }, _sum: { amount: true } }),
    prisma.$queryRaw<Array<{ productId: string; quantity: Prisma.Decimal }>>(Prisma.sql`SELECT sold.productId, GREATEST(sold.quantity - COALESCE(returned.quantity, 0), 0) AS quantity FROM (SELECT si.productId, SUM(si.quantity) AS quantity FROM SaleItem si INNER JOIN Sale s ON s.id = si.saleId WHERE s.status IN ('COMPLETED', 'PARTIAL_RETURN', 'RETURNED') AND s.saleDate >= ${from} AND s.saleDate < ${tomorrow} ${scopeStoreId ? Prisma.sql`AND s.storeId = ${scopeStoreId}` : Prisma.empty} GROUP BY si.productId) sold INNER JOIN Product p ON p.id = sold.productId LEFT JOIN (SELECT si.productId, SUM(ri.quantity) AS quantity FROM SaleReturnItem ri INNER JOIN SaleReturn sr ON sr.id = ri.returnId INNER JOIN SaleItem si ON si.id = ri.saleItemId INNER JOIN Sale s ON s.id = sr.saleId WHERE s.status IN ('COMPLETED', 'PARTIAL_RETURN', 'RETURNED') AND s.saleDate >= ${from} AND s.saleDate < ${tomorrow} ${scopeStoreId ? Prisma.sql`AND s.storeId = ${scopeStoreId}` : Prisma.empty} GROUP BY si.productId) returned ON returned.productId = sold.productId WHERE p.status = 'ACTIVE' AND sold.quantity > COALESCE(returned.quantity, 0) ORDER BY quantity DESC LIMIT 5`),
    prisma.$queryRaw<Array<{ count: bigint }>>(Prisma.sql`SELECT COUNT(*) AS count FROM Inventory i INNER JOIN Product p ON p.id = i.productId INNER JOIN Warehouse w ON w.id = i.warehouseId WHERE p.status = 'ACTIVE' AND (i.quantity - i.reservedQuantity) <= p.minimumStock ${scopeStoreId ? Prisma.sql`AND w.storeId = ${scopeStoreId}` : Prisma.empty}`),
  ]);
  const lowStockIds = await prisma.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT i.id FROM Inventory i INNER JOIN Product p ON p.id = i.productId INNER JOIN Warehouse w ON w.id = i.warehouseId WHERE p.status = 'ACTIVE' AND (i.quantity - i.reservedQuantity) <= p.minimumStock ${scopeStoreId ? Prisma.sql`AND w.storeId = ${scopeStoreId}` : Prisma.empty} ORDER BY (i.quantity - i.reservedQuantity) ASC, p.name ASC LIMIT 6`);
  const lowStockRows = lowStockIds.length ? await prisma.inventory.findMany({ where: { id: { in: lowStockIds.map((row) => row.id) } }, select: { quantity: true, reservedQuantity: true, warehouse: { select: { name: true } }, product: { select: { id: true, name: true, sku: true, minimumStock: true } } } }) : [];
  const lowStock = lowStockRows.map((row) => ({ ...row, available: calculateAvailableQuantity(row.quantity, row.reservedQuantity) }));
  const stockValue = inventoryValueRows[0]?.stockValue ?? new Prisma.Decimal(0);
  const trendByDay = new Map(weekSales.map(({ dayKey, total }) => [dayKey, Number(total)]));
  const chart = Array.from({ length: 7 }, (_, index) => { const date = new Date(from.getTime() + index * 24 * 60 * 60 * 1000); const key = businessDayKey(date); return { day: date.toLocaleDateString("en", { weekday: "short", timeZone: "Asia/Jakarta" }), total: trendByDay.get(key) ?? 0 }; });
  const topProducts = topProductRows.length ? await prisma.product.findMany({ where: { id: { in: topProductRows.map((row) => row.productId) } }, select: { id: true, name: true, sku: true } }) : [];
  const topProductById = new Map(topProducts.map((product) => [product.id, product]));
  const cards = [
    { label: "Today's sales", value: formatCurrency(String(todaySales._sum.grandTotal ?? 0)), note: `${todayTransactions} completed transactions`, icon: CircleDollarSign, tint: "bg-emerald-50 text-emerald-700" },
    { label: "Active products", value: productCount.toLocaleString("id-ID"), note: "Items in catalog", icon: Package, tint: "bg-blue-50 text-blue-700" },
    { label: "Low stock", value: Number(lowStockCountRows[0]?.count ?? 0).toLocaleString("id-ID"), note: "At or below minimum available", icon: Boxes, tint: "bg-amber-50 text-amber-700" },
    { label: "Pending purchases", value: pendingPurchases.toLocaleString("id-ID"), note: `${pendingOrders} draft orders`, icon: ShoppingBag, tint: "bg-violet-50 text-violet-700" },
    { label: "Sales this week", value: formatCurrency(weekSummary._sum.grandTotal?.toString() ?? "0"), note: `${weekSummary._count._all} completed transactions`, icon: CircleDollarSign, tint: "bg-cyan-50 text-cyan-700" },
    { label: "Sales this month", value: formatCurrency(monthSales._sum.grandTotal?.toString() ?? "0"), note: `${monthSales._count._all} completed transactions`, icon: CircleDollarSign, tint: "bg-indigo-50 text-indigo-700" },
    { label: "Refunds this month", value: formatCurrency(monthRefunds._sum.amount?.toString() ?? "0"), note: "Settled refunds", icon: CircleDollarSign, tint: "bg-rose-50 text-rose-700" },
  ];
  return <div className="space-y-6">
    <PageHeader title="Dashboard" description={`Good day, ${user.name.split(" ")[0]}. Here is your operations snapshot.`} action={<div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">{store ? `${store.name} · ${store.code}` : "All stores"} · {formatDate(new Date())}</div>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, note, icon: Icon, tint }) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><span className={`rounded-lg p-2 ${tint}`}><Icon size={18}/></span></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4"><h2 className="font-semibold">Sales summary</h2><p className="mt-1 text-xs text-slate-500">Completed sales · last 7 days</p></div><SalesChart data={chart}/></section><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Inventory snapshot</h2><p className="mt-1 text-xs text-slate-500">Current stock value at recorded average cost</p></div><ShoppingCart size={18} className="text-slate-400"/></div><p className="text-2xl font-semibold">{formatCurrency(stockValue.toString())}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Customers</p><p className="mt-1 text-lg font-semibold">{customerCount.toLocaleString("id-ID")}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Suppliers</p><p className="mt-1 text-lg font-semibold">{supplierCount.toLocaleString("id-ID")}</p></div></div></section></div>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Recent sales</h2><p className="text-xs text-slate-500">Latest completed transactions</p></div><Link href="/sales" className="inline-flex items-center gap-1 text-sm font-medium text-emerald-800">All sales <ArrowRight size={15}/></Link></div><TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Invoice", "Customer", "Date", "Status", "Payment", "Amount"].map((label)=><th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{recentSales.map((sale)=><tr key={sale.invoiceNumber}><td className="px-4 py-3 font-medium">{sale.invoiceNumber}</td><td className="px-4 py-3 text-slate-600">{sale.customer?.name ?? "Walk-in customer"}</td><td className="px-4 py-3 text-slate-600">{formatDate(sale.saleDate)}</td><td className="px-4 py-3"><StatusBadge value={sale.status}/></td><td className="px-4 py-3"><StatusBadge value={sale.paymentStatus}/></td><td className="px-4 py-3 text-right font-medium">{formatCurrency(sale.grandTotal.toString())}</td></tr>)}</tbody></TableFrame>{!recentSales.length && <p className="rounded-b-xl border border-t-0 border-slate-200 bg-white py-8 text-center text-sm text-slate-500">No completed sales yet.</p>}</section>
    <section><h2 className="mb-3 font-semibold">Top selling products · last 7 days</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{topProductRows.map((row)=>{const product=topProductById.get(row.productId);return <article key={row.productId} className="rounded-xl border border-slate-200 bg-white p-4"><p className="truncate text-sm font-medium">{product?.name??"Product"}</p><p className="mt-1 text-xs text-slate-500">{product?.sku}</p><p className="mt-3 text-lg font-semibold">{row.quantity.toString()}</p><p className="text-xs text-slate-500">net units sold after returns</p></article>})}{!topProductRows.length&&<p className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500">No product sales this week.</p>}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Low stock items</h2><Link href="/inventory" className="text-sm text-emerald-800">View inventory</Link></div><div className="rounded-xl border border-slate-200 bg-white">{lowStock.length ? lowStock.map((row)=><div key={`${row.product.id}:${row.warehouse.name}`} className="flex items-center justify-between border-b border-slate-100 px-4 py-3 last:border-0"><div><p className="text-sm font-medium">{row.product.name}</p><p className="text-xs text-slate-500">{row.product.sku} · {row.warehouse.name}</p></div><p className="text-sm font-semibold text-amber-700">{row.available.toString()} <span className="font-normal text-slate-500">/ min {row.product.minimumStock.toString()}</span></p></div>) : <p className="p-8 text-center text-sm text-slate-500">No low stock items.</p>}</div></section><section><div className="mb-3 flex items-center gap-2"><Activity size={17}/><h2 className="font-semibold">Recent activity</h2></div><div className="rounded-xl border border-slate-200 bg-white">{activity.length ? activity.map((item,index)=><div key={`${item.createdAt.toISOString()}-${index}`} className="flex items-start justify-between gap-3 border-b border-slate-100 px-4 py-3 last:border-0"><div><p className="text-sm font-medium">{item.action} · {item.module}</p><p className="text-xs text-slate-500">{item.entity ?? "Record"}</p></div><time className="whitespace-nowrap text-xs text-slate-500">{formatDate(item.createdAt)}</time></div>) : <p className="p-8 text-center text-sm text-slate-500">No activity recorded yet.</p>}</div></section></div>
  </div>;
}
