import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { authorizedStoreScopeId, requirePermission, hasPermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { approvePurchaseAction, receivePurchaseAction, returnPurchaseAction } from "@/app/(dashboard)/purchases/actions";
import { formatCurrency, formatDate } from "@/lib/utils";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";

export default async function PurchaseDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{received?:string;returned?:string;error?:string}>}){
 const user=await requirePermission("purchase.view");const {id}=await params;const query=await searchParams;const storeId=authorizedStoreScopeId(user);
 const purchase=await prisma.purchase.findFirst({where:{id,...(storeId?{storeId}:{})},include:{supplier:true,store:true,warehouse:true,createdBy:{select:{name:true}},items:{include:{product:{select:{name:true,sku:true}}}},payments:true,returns:{orderBy:{createdAt:"desc"}}}});if(!purchase)notFound();
 const remaining=purchase.items.filter((item)=>item.receivedQuantity.lessThan(item.quantity));
 return <div><PageHeader title={purchase.invoiceNumber} description={`${purchase.supplier.name} · ${formatDate(purchase.purchaseDate)}`} action={<Link href="/purchases" className="text-sm text-emerald-800 hover:underline">Back to purchases</Link>}/>{query.received&&<p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Receiving saved and stock updated.</p>}{query.returned&&<p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Return processed and stock adjusted.</p>}{query.error&&<p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">That operation could not be completed. Check quantities and status.</p>}
  <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Supplier</p><p className="mt-1 font-medium">{purchase.supplier.name}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Destination</p><p className="mt-1 font-medium">{purchase.store.name} · {purchase.warehouse.name}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Status</p><div className="mt-2"><StatusBadge value={purchase.status}/></div></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Created by</p><p className="mt-1 font-medium">{purchase.createdBy.name}</p></div></div>
  <TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Product","SKU","Ordered","Received","Unit cost","Line total"].map((label)=><th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{purchase.items.map((item)=><tr key={item.id}><td className="px-4 py-3 font-medium">{item.product.name}</td><td className="px-4 py-3 font-mono text-xs">{item.product.sku}</td><td className="px-4 py-3">{item.quantity.toString()}</td><td className="px-4 py-3">{item.receivedQuantity.toString()}</td><td className="px-4 py-3">{formatCurrency(item.unitCost.toString())}</td><td className="px-4 py-3 text-right">{formatCurrency(item.subtotal.toString())}</td></tr>)}</tbody></TableFrame>
  <div className="ml-auto mt-4 max-w-sm space-y-2 rounded-xl border border-slate-200 bg-white p-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatCurrency(purchase.subtotal.toString())}</span></div><div className="flex justify-between"><span>Discount</span><span>{formatCurrency(purchase.discount.toString())}</span></div><div className="flex justify-between"><span>Tax + shipping</span><span>{formatCurrency(purchase.tax.plus(purchase.shipping).toString())}</span></div><div className="flex justify-between border-t border-slate-100 pt-2 text-base font-semibold"><span>Total</span><span>{formatCurrency(purchase.grandTotal.toString())}</span></div></div>
  {hasPermission(user,"purchase.approve")&&(purchase.status==="PENDING"||purchase.status==="DRAFT")&&<form action={approvePurchaseAction} className="mt-5"><input type="hidden" name="id" value={purchase.id}/><button className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-medium text-white">Approve purchase</button></form>}
  {hasPermission(user,"purchase.receive")&&remaining.length>0&&(purchase.status==="APPROVED"||purchase.status==="PARTIALLY_RECEIVED")&&<form action={receivePurchaseAction} className="mt-5 rounded-xl border border-slate-200 bg-white p-4"><input type="hidden" name="id" value={purchase.id}/><input type="hidden" name="requestKey" value={randomUUID()}/><h2 className="mb-3 font-semibold">Receive stock</h2><div className="space-y-3">{remaining.map((item)=><label key={item.id} className="grid items-center gap-2 text-sm sm:grid-cols-[1fr_160px]"><span>{item.product.name}<span className="block text-xs text-slate-500">Remaining {item.quantity.minus(item.receivedQuantity).toString()}</span></span><input name={`receive-${item.id}`} type="number" min="0" max={item.quantity.minus(item.receivedQuantity).toString()} step="0.001" defaultValue="0" className="h-10 rounded-lg border border-slate-300 px-3"/></label>)}</div><button className="mt-4 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-medium text-white">Save receiving quantities</button></form>}
  {hasPermission(user,"purchase.return")&&(purchase.status==="RECEIVED"||purchase.status==="PARTIALLY_RECEIVED"||purchase.status==="COMPLETED")&&<form action={returnPurchaseAction} className="mt-5 grid gap-3 rounded-xl border border-amber-200 bg-amber-50/50 p-4 sm:grid-cols-4"><h2 className="font-semibold sm:col-span-4">Return received stock</h2><input type="hidden" name="id" value={purchase.id}/><select name="purchaseItemId" required className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm sm:col-span-2"><option value="">Select item</option>{purchase.items.filter((item)=>item.receivedQuantity.greaterThan(0)).map((item)=><option key={item.id} value={item.id}>{item.product.name} · received {item.receivedQuantity.toString()}</option>)}</select><input name="quantity" type="number" min="0.001" step="0.001" required placeholder="Return quantity" className="h-10 rounded-lg border border-slate-300 px-3 text-sm"/><input name="reason" required maxLength={2000} placeholder="Return reason" className="h-10 rounded-lg border border-slate-300 px-3 text-sm"/><button className="rounded-lg bg-amber-700 px-4 py-2 text-sm font-medium text-white sm:col-span-4">Process return</button></form>}
 </div>;
}
