import Link from "next/link";
import { redirect } from "next/navigation";
import { requirePermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { createProduct } from "@/lib/actions/catalog";
import { PageHeader } from "@/components/ui/page-header";

export default async function NewProductPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requirePermission("product.create");
  const { error } = await searchParams;
  const [categories, brands, units] = await Promise.all([prisma.category.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.brand.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.unit.findMany({ orderBy: { name: "asc" } })]);
  if (!units.length) redirect("/products?error=missing-unit");
  const field="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm";
  return <div className="max-w-3xl"><PageHeader title="New product" description="Add an item to the shared product catalog."/><form action={createProduct} className="space-y-5 rounded-xl border border-slate-200 bg-white p-5 sm:p-7">{error&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error==="duplicate"?"SKU or barcode already exists.":"Check each field and try again."}</p>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Product name<input required name="name" maxLength={180} className={`${field} mt-1`}/></label><label className="text-sm font-medium">SKU<input required name="sku" maxLength={60} className={`${field} mt-1`}/></label><label className="text-sm font-medium">Barcode<input name="barcode" maxLength={100} className={`${field} mt-1`}/></label><label className="text-sm font-medium">Unit<select name="unitId" required className={`${field} mt-1`}>{units.map((unit)=><option key={unit.id} value={unit.id}>{unit.name} ({unit.symbol})</option>)}</select></label><label className="text-sm font-medium">Category<select name="categoryId" className={`${field} mt-1`}><option value="">No category</option>{categories.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Brand<select name="brandId" className={`${field} mt-1`}><option value="">No brand</option>{brands.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Cost price (IDR)<input required name="costPrice" type="number" min="0" step="0.01" defaultValue="0" className={`${field} mt-1`}/></label><label className="text-sm font-medium">Selling price (IDR)<input required name="sellingPrice" type="number" min="0.01" step="0.01" className={`${field} mt-1`}/></label><label className="text-sm font-medium">Minimum stock<input required name="minimumStock" type="number" min="0" step="0.001" defaultValue="0" className={`${field} mt-1`}/></label><label className="text-sm font-medium">Tax rate (%)<input required name="taxRate" type="number" min="0" max="100" step="0.001" defaultValue="0" className={`${field} mt-1`}/></label></div><label className="block text-sm font-medium">Description<textarea name="description" rows={3} maxLength={4000} className={`${field} mt-1 h-auto py-2`}/></label><div className="flex justify-end gap-2"><Link href="/products" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm">Cancel</Link><button className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-medium text-white">Create product</button></div></form></div>;
}
