import Link from "next/link";
import { Plus } from "lucide-react";
import { authorizedStoreScopeId, requirePermission, hasPermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";

export default async function PurchasesPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;error?:string}>}){
 const user=await requirePermission("purchase.view");const {q="",status="ALL",error}=await searchParams;const storeId=authorizedStoreScopeId(user);
 const allowedStatuses=["DRAFT","PENDING","APPROVED","PARTIALLY_RECEIVED","RECEIVED","COMPLETED","CANCELLED"] as const;
 if ((!allowedStatuses.includes(status as typeof allowedStatuses[number])&&status!=="ALL")||q.length>100) return <div><PageHeader title="Purchases" description="Purchase orders, receiving, and supplier returns."/><p role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">Invalid purchase filters. Check the status and search length.</p></div>;
 const purchases=await prisma.purchase.findMany({where:{...(storeId?{storeId}:{}),...(status==="ALL"?{}:{status:status as typeof allowedStatuses[number]}),...(q?{OR:[{invoiceNumber:{contains:q}},{supplier:{name:{contains:q}}}]}:{})},orderBy:{purchaseDate:"desc"},take:100,include:{supplier:{select:{name:true}},store:{select:{name:true}},warehouse:{select:{name:true}},createdBy:{select:{name:true}}}});
 return <div><PageHeader title="Purchases" description="Purchase orders, receiving, and supplier returns." action={hasPermission(user,"purchase.create")?<Link href="/purchases/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-medium text-white"><Plus size={16}/> New purchase</Link>:null}/>{error&&<p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">That operation could not be completed.</p>}<form className="mb-4 grid gap-2 sm:grid-cols-[1fr_180px_auto]"><input name="q" defaultValue={q} placeholder="Purchase number or supplier" className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"/><select name="status" defaultValue={status} className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">All statuses</option>{["DRAFT","PENDING","APPROVED","PARTIALLY_RECEIVED","RECEIVED","COMPLETED","CANCELLED"].map((item)=><option key={item}>{item}</option>)}</select><button className="rounded-lg border border-slate-300 bg-white px-4 text-sm">Filter</button></form>{purchases.length?<TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Purchase","Supplier","Date","Store / warehouse","Created by","Total","Status"].map((item)=><th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{purchases.map((purchase)=><tr key={purchase.id}><td className="px-4 py-3 font-medium"><Link href={`/purchases/${purchase.id}`} className="text-emerald-800 hover:underline">{purchase.invoiceNumber}</Link></td><td className="px-4 py-3">{purchase.supplier.name}</td><td className="px-4 py-3 text-slate-600">{formatDate(purchase.purchaseDate)}</td><td className="px-4 py-3">{purchase.store.name} · {purchase.warehouse.name}</td><td className="px-4 py-3">{purchase.createdBy.name}</td><td className="px-4 py-3 text-right">{formatCurrency(purchase.grandTotal.toString())}</td><td className="px-4 py-3"><StatusBadge value={purchase.status}/></td></tr>)}</tbody></TableFrame>:<p className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No purchases match those filters.</p>}</div>;
}
