import Link from "next/link";
import { Plus } from "lucide-react";
import { authorizedStoreScopeId, requirePermission, hasPermission } from "@/lib/auth/authorization";
import { prisma } from "@/lib/db/prisma";
import { PageHeader, StatusBadge, TableFrame } from "@/components/ui/page-header";

export default async function SuppliersPage({ searchParams }: { searchParams: Promise<{ q?: string; created?: string }> }) {
  const user = await requirePermission("supplier.manage"); const storeId=authorizedStoreScopeId(user); const { q="", created }=await searchParams;
  const suppliers=await prisma.supplier.findMany({where:q?{OR:[{name:{contains:q}},{supplierCode:{contains:q}},{email:{contains:q}},{phone:{contains:q}}]}:{},orderBy:{name:"asc"},take:100,include:{_count:{select:{purchases:{where:storeId?{storeId}:{}}}}}});
  return <div><PageHeader title="Suppliers" description="Supplier contacts and purchase relationships." action={hasPermission(user,"supplier.manage")?<Link href="/suppliers/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-medium text-white"><Plus size={16}/> Add supplier</Link>:null}/>{created&&<p role="status" className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Supplier {created} created.</p>}<form className="mb-4 flex gap-2"><input name="q" defaultValue={q} placeholder="Search supplier name, code, email, phone" className="h-10 min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 text-sm"/><button className="rounded-lg border border-slate-300 bg-white px-4 text-sm">Search</button></form>{suppliers.length?<TableFrame><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Code","Supplier","Contact","Purchases","Status"].map((name)=><th key={name} className="px-4 py-3 font-medium">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{suppliers.map((supplier)=><tr key={supplier.id}><td className="px-4 py-3 font-mono text-xs">{supplier.supplierCode}</td><td className="px-4 py-3 font-medium"><Link href={`/suppliers/${supplier.id}`} className="text-emerald-800 hover:underline">{supplier.name}</Link></td><td className="px-4 py-3 text-slate-600">{supplier.contactPerson??supplier.email??supplier.phone??"—"}</td><td className="px-4 py-3">{supplier._count.purchases}</td><td className="px-4 py-3"><StatusBadge value={supplier.status}/></td></tr>)}</tbody></TableFrame>:<p className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No suppliers match this search.</p>}</div>;
}
